don't check changes on a merge commit

diff --git a/.github/workflows/update-repocontents.yaml b/.github/workflows/update-repocontents.yaml
--- a/.github/workflows/update-repocontents.yaml
+++ b/.github/workflows/update-repocontents.yaml
@@ -52,16 +52,16 @@ jobs:
             echo "changed: $file"
           done
 
-      - name: Assert only one file was changed.
-        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
-        if: steps.changed-files.outputs.everything_all_changed_files_count != 1
-        run: |
-          echo "::error::More than one file was changed." && exit 1
+      #- name: Assert only one file was changed.
+      #  # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
+      #  if: steps.changed-files.outputs.everything_all_changed_files_count != 1
+      #  run: |
+      #    echo "::error::More than one file was changed." && exit 1
 
-      - name: Assert file changed was a netid file.
-        if: steps.changed-files.outputs.netids_all_changed_files_count != 1
-        run: |
-          echo "::error::Changed a file other than your netid markdown." && exit 1
+      #- name: Assert file changed was a netid file.
+      #  if: steps.changed-files.outputs.netids_all_changed_files_count != 1
+      #  run: |
+      #    echo "::error::Changed a file other than your netid markdown." && exit 1
 
       - name: Verify script settings
         run: |
