try specific sha for diff

diff --git a/.github/workflows/update-repocontents.yaml b/.github/workflows/update-repocontents.yaml
--- a/.github/workflows/update-repocontents.yaml
+++ b/.github/workflows/update-repocontents.yaml
@@ -31,8 +31,8 @@ jobs:
       #- uses: jwalton/gh-find-current-pr@v1
       #  id: prfinder
 
-      #- run: echo "Your PR is ${PR}"
-      #  if: success() && steps.findPr.outputs.number
+      #- run: echo "Current PR is ${PR}"
+      #  #if: success() && steps.findPr.outputs.number
       #  env:
       #    PR_NUMBER: ${{ steps.findPr.outputs.pr }}
 
@@ -40,6 +40,7 @@ jobs:
         id: changed-files
         uses: tj-actions/changed-files@v37
         with:
+          sha: ${{ github.event.pull_request.head.sha }}
           files_yaml: |
             everything:
               - '*'
@@ -52,16 +53,16 @@ jobs:
             echo "changed: $file"
           done
 
-      #- name: Assert only one file was changed.
-      #  # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
-      #  if: steps.changed-files.outputs.everything_all_changed_files_count != 1
-      #  run: |
-      #    echo "::error::More than one file was changed." && exit 1
+      - name: Assert only one file was changed.
+        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
+        if: steps.changed-files.outputs.everything_all_changed_files_count != 1
+        run: |
+          echo "::error::More than one file was changed." && exit 1
 
-      #- name: Assert file changed was a netid file.
-      #  if: steps.changed-files.outputs.netids_all_changed_files_count != 1
-      #  run: |
-      #    echo "::error::Changed a file other than your netid markdown." && exit 1
+      - name: Assert file changed was a netid file.
+        if: steps.changed-files.outputs.netids_all_changed_files_count != 1
+        run: |
+          echo "::error::Changed a file other than your netid markdown." && exit 1
 
       - name: Verify script settings
         run: |
