list changed files

diff --git a/.github/workflows/verify-netid-file.yaml b/.github/workflows/verify-netid-file.yaml
--- a/.github/workflows/verify-netid-file.yaml
+++ b/.github/workflows/verify-netid-file.yaml
@@ -18,8 +18,7 @@ jobs:
         with:
           fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
 
-      # Example 1
-      - name: Get all test, doc and src files that have changed
+      - name: Get the files that were changed.
         id: changed-files
         uses: tj-actions/changed-files@v37
         with:
@@ -28,6 +27,12 @@ jobs:
               - '**/*'
             netids:
               - '[a-z]*.md'
+
+      - name: List all changed files
+        run: |
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            echo "$file was changed"
+          done
 
       - name: Assert only one file was changed.
         # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
@@ -38,4 +43,4 @@ jobs:
       - name: Assert file changed was a netid file.
         if: steps.changed-files.outputs.netids_changed_files_count != 1
         run: |
-          echo "::error::More than one file was changed." && exit 1
+          echo "::error::Changed a file other than your netid markdown." && exit 1
